package types

import "cosmossdk.io/errors"

var (
	ErrucapabilitiesAlreadyRegistered     = errors.Register(ModuleName, 1100, "capabilities already registered")
	ErrucapabilitiesNotFound              = errors.Register(ModuleName, 1101, "capabilities not found")
	ErrInsufficientStake          = errors.Register(ModuleName, 1102, "insufficient stake amount")
	ErrucapabilitiesSuspended             = errors.Register(ModuleName, 1103, "capabilities is suspended")
	ErrHeartbeatTooFrequent       = errors.Register(ModuleName, 1104, "heartbeat sent too frequently")
	ErrChallengeNotActive         = errors.Register(ModuleName, 1105, "no active AI challenge")
	ErrChallengeExpired           = errors.Register(ModuleName, 1106, "AI challenge submission window expired")
	ErrAlreadySubmitted           = errors.Register(ModuleName, 1107, "already submitted response for this epoch")
	ErrInvalidReveal              = errors.Register(ModuleName, 1108, "reveal does not match commit hash")
	ErrReputationTooLow           = errors.Register(ModuleName, 1109, "reputation below minimum threshold")
	ErrDeregisterCooldown         = errors.Register(ModuleName, 1110, "capabilities in deregister cooldown period")
	ErrDeregisterAlreadyQueued    = errors.Register(ModuleName, 1111, "deregister already requested")
	ErrChallengeWindowClosed      = errors.Register(ModuleName, 1112, "challenge submission window closed")
	ErrucapabilitiesOffline               = errors.Register(ModuleName, 1113, "capabilities is offline")
	ErrRevealTooEarly             = errors.Register(ModuleName, 1114, "reveal phase has not started yet")
	ErrRevealWindowClosed         = errors.Register(ModuleName, 1115, "reveal window has closed")
	ErrAlreadyEvaluated           = errors.Register(ModuleName, 1116, "challenge already evaluated")
	ErrDailyRegisterLimitExceeded = errors.Register(ModuleName, 1117, "daily registration limit exceeded (max 3 per address per day)")
	ErrInvalidStakeDenom          = errors.Register(ModuleName, 1118, "invalid stake denom")
	ErrStakeAmountMustBePositive  = errors.Register(ModuleName, 1119, "stake amount must be positive")
	ErrValidatorRequired          = errors.Register(ModuleName, 1120, "operation requires an active bonded validator")
	ErrBelowMinimumStake          = errors.Register(ModuleName, 1121, "stake would fall below minimum registration stake")
	ErrPendingReduceExists        = errors.Register(ModuleName, 1122, "a pending stake reduction already exists")
	ErrNoReducePending            = errors.Register(ModuleName, 1123, "no pending stake reduction to claim")
	ErrReduceNotUnlocked          = errors.Register(ModuleName, 1124, "pending stake reduction has not reached unlock height")
	ErrServiceNameInvalid          = errors.Register(ModuleName, 1125, "service name is invalid (alphanumeric and hyphens only)")
	ErrServiceNotFound             = errors.Register(ModuleName, 1126, "service not found")
	ErrTaskNotFound                = errors.Register(ModuleName, 1127, "task not found")
	ErrTaskAlreadyAssigned         = errors.Register(ModuleName, 1128, "task already assigned")
	ErrInsufficientPayment        = errors.Register(ModuleName, 1129, "insufficient payment for task")
	ErrToolNotFound                = errors.Register(ModuleName, 1130, "tool not found")
	ErrUnauthorized               = errors.Register(ModuleName, 1131, "unauthorized")
	ErrInvalidToolDefinition       = errors.Register(ModuleName, 1132, "invalid tool definition")
	ErrInvalidDenom              = errors.Register(ModuleName, 1133, "invalid denomination")
	ErrVaultNotFound             = errors.Register(ModuleName, 1134, "stablecoin vault not found")
	ErrInsufficientLiquidity    = errors.Register(ModuleName, 1135, "insufficient liquidity")
	ErrPriceBelowFloor            = errors.Register(ModuleName, 1136, "price below floor")
	ErrPriceAboveCeil            = errors.Register(ModuleName, 1137, "price above ceiling")
	ErrEscrowNotFound           = errors.Register(ModuleName, 1138, "escrow not found")
	ErrEscrowInsufficientFunds  = errors.Register(ModuleName, 1139, "insufficient funds in escrow")
	ErrEscrowExpired            = errors.Register(ModuleName, 1140, "escrow expired")
	ErrAlreadyResolved         = errors.Register(ModuleName, 1141, "already resolved")
	ErrProposalNotFound        = errors.Register(ModuleName, 1142, "proposal not found")
	ErrVoteAlreadyCast        = errors.Register(ModuleName, 1143, "vote already cast")
	ErrInvalidProposal       = errors.Register(ModuleName, 1144, "invalid proposal")
)